Make image bbappends dynamically parsed
core-image-hailo and core-image-hailo-dev live in meta-hailo-soc,
and this layer can mostly build without it.

Except for these bbappend files, because the previous warnings
are hard errors in Yocto 5.3:

ERROR: No recipes in default available for:
  .../layers/meta-hailo/meta-hailo-vpu/recipes-core/images/core-image-hailo-dev.bbappend
  .../layers/meta-hailo/meta-hailo-vpu/recipes-core/images/core-image-hailo.bbappend

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>